### ISSUE TITLE
Not Scalable

### ISSUE THREAD

**Issue by stevemac00** [cflurin/homebridge-mvc#1]
Thanks for sharing. The plugin was easy to begin a test and is functional but unfortunately the design does not scale well.

For example, the MQTT device subscribes to topic `homebridge/from/get` to receive any responses and requests. That's workable for a few but I have twenty ESP8266 MQTT Devices. That means every device on the network receives the message because they all have to subscribe and publish on the same topics.

This could've been avoided if the name property were in the topic instead of the payload.

**Comment by cflurin** [comment]
I didn't update this repository for a while. Take a look at: https://github.com/cflurin/homebridge-mqtt

There is a setting in `config.json`:
```js
"topic_type": "multiple",

or

"topic_type": "single",
```

**Comment by stevemac00** [comment]
Sorry for spamming you. I totally missed that option.
